// Generated from the images in public/images/template, by Tabbied's image
// pipeline. Do not edit by hand.
//
// Ids of the files sitting in public/images/template. A template slot whose id
// appears here renders the generated image; every other slot keeps showing its
// image prompt card, so the pages stay complete while a run is only
// partly filled in.
export const GENERATED_IMAGES: readonly string[] = [
  'react__ember-and-oak__about-0',
  'react__ember-and-oak__alt-0',
  'react__ember-and-oak__alt-1',
  'react__ember-and-oak__card-0',
  'react__ember-and-oak__card-1',
  'react__ember-and-oak__card-2',
  'react__ember-and-oak__gallery-0',
  'react__ember-and-oak__gallery-1',
  'react__ember-and-oak__gallery-2',
  'react__ember-and-oak__gallery-3',
  'react__ember-and-oak__team-0',
  'react__ember-and-oak__team-1',
  'react__ember-and-oak__team-2',
  'react__ember-and-oak__team-3',
  'react__facet__about-0',
  'react__facet__alt-0',
  'react__facet__alt-1',
  'react__facet__card-0',
  'react__facet__card-1',
  'react__facet__card-2',
  'react__facet__gallery-0',
  'react__facet__gallery-1',
  'react__facet__gallery-2',
  'react__facet__gallery-3',
  'react__nocturne__about-0',
  'react__nocturne__alt-0',
  'react__nocturne__alt-1',
  'react__nocturne__card-0',
  'react__nocturne__card-1',
  'react__nocturne__card-2',
  'react__nocturne__gallery-0',
  'react__nocturne__gallery-1',
  'react__nocturne__gallery-2',
  'react__nocturne__gallery-3',
  'react__solstice__alt-0',
  'react__solstice__alt-1',
  'react__solstice__card-0',
  'react__solstice__card-1',
  'react__solstice__card-2',
  'react__solstice__gallery-0',
  'react__solstice__gallery-1',
  'react__solstice__gallery-2',
  'react__solstice__gallery-3',
  'react__verdant__about-0',
  'react__verdant__alt-0',
  'react__verdant__alt-1',
  'react__verdant__card-0',
  'react__verdant__card-1',
  'react__verdant__card-2',
  'react__verdant__gallery-0',
  'react__verdant__gallery-1',
  'react__verdant__gallery-2',
  'react__verdant__gallery-3',
];
