// Generates src/patterns.generated.ts and catalog.json from patterns/*.json.
//
// Embedding the presets as one named `const` per pattern (instead of reading
// JSON at runtime) removes any node:fs dependency from library code, gives
// consumers compile-time `PatternSlug` types, and lets bundlers tree-shake the
// presets a consumer never imports. Run via `npm run codegen` (also part of
// `npm run build`).
//
// catalog.json is the same data reshaped for *readers* rather than bundlers:
// one entry per design with the metadata needed to pick one and configure it,
// minus the css-doodle source. It ships in the published tarball and is
// served by the site, so an AI coding assistant can search the designs by
// description instead of guessing slugs. See scripts/generate-llms.mjs at the
// repo root, which builds the site's llms.txt from it.
import { readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { validateDesignMetadata } from './catalog-vocabulary.mjs';

const packageRoot = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const patternsDir = path.join(packageRoot, 'patterns');
const outFile = path.join(packageRoot, 'src', 'patterns.generated.ts');
const catalogFile = path.join(packageRoot, 'catalog.json');

// ES reserved words that pass the lowercase-alphanumeric slug check, plus the
// generated module's own exports.
const RESERVED_SLUGS = new Set([
  'break', 'case', 'catch', 'class', 'const', 'continue', 'debugger',
  'default', 'delete', 'do', 'else', 'enum', 'export', 'extends', 'false',
  'finally', 'for', 'function', 'if', 'implements', 'import', 'in',
  'instanceof', 'interface', 'let', 'new', 'null', 'package', 'private',
  'protected', 'public', 'return', 'static', 'super', 'switch', 'this',
  'throw', 'true', 'try', 'typeof', 'var', 'void', 'while', 'with', 'yield',
  'await', 'patterns', 'ispatternslug',
  // Restricted in strict mode, which a module always is.
  'eval', 'arguments',
]);

const fileNames = (await readdir(patternsDir))
  .filter((fileName) => fileName.endsWith('.json'))
  .sort();

const patterns = await Promise.all(
  fileNames.map(async (fileName) => {
    const definition = JSON.parse(
      await readFile(path.join(patternsDir, fileName), 'utf-8')
    );
    const slug = fileName.replace(/\.json$/, '');

    if (definition.slug !== slug) {
      throw new Error(
        `patterns/${fileName}: "slug" is "${definition.slug}" but must match the file name`
      );
    }
    if (!/^[a-z][a-z0-9]*$/.test(slug)) {
      throw new Error(
        `patterns/${fileName}: slug must be a lowercase alphanumeric identifier`
      );
    }
    // Each slug becomes `export const <slug>`, so reserved words (and the
    // module's own identifiers) would generate a syntax/duplicate error.
    if (RESERVED_SLUGS.has(slug)) {
      throw new Error(
        `patterns/${fileName}: slug "${slug}" is a reserved identifier and cannot be used`
      );
    }

    return definition;
  })
);

const header = `// AUTO-GENERATED by scripts/codegen.mjs from patterns/*.json - do not edit.
// Regenerate with \`npm run codegen\` (runs automatically as part of \`npm run build\`).
import type { PatternDefinition } from './core/types.js';
`;

// Catalog-only metadata: authored in patterns/*.json for the searchable
// index, but stripped from the runtime bundle - rendering never reads it, and
// PatternDefinition deliberately doesn't carry it (tsc would reject the
// generated literals if it leaked through).
const CATALOG_ONLY_FIELDS = ['tags', 'mood', 'density', 'goodFor'];

// Every design must carry complete, in-vocabulary metadata - the catalog is
// queried on these enums, so a design without them is invisible to the tools
// the catalog exists for. Fail the build listing every problem at once.
const metadataErrors = patterns.flatMap((definition) =>
  validateDesignMetadata(definition)
);
if (metadataErrors.length) {
  for (const error of metadataErrors) console.error(`codegen: ${error}`);
  throw new Error(
    `codegen: ${metadataErrors.length} catalog-metadata problem(s) - see scripts/catalog-vocabulary.mjs`
  );
}

const runtimeDefinition = (definition) =>
  Object.fromEntries(
    Object.entries(definition).filter(
      ([key]) => !CATALOG_ONLY_FIELDS.includes(key)
    )
  );

const consts = patterns
  .map(
    (definition) =>
      `export const ${definition.slug}: PatternDefinition = ${JSON.stringify(
        runtimeDefinition(definition),
        null,
        2
      )};`
  )
  .join('\n\n');

const record = `export const patterns = {
${patterns.map(({ slug }) => `  ${slug},`).join('\n')}
} as const;

export type PatternSlug = keyof typeof patterns;

export function isPatternSlug(value: string): value is PatternSlug {
  return Object.prototype.hasOwnProperty.call(patterns, value);
}
`;

await writeFile(outFile, `${header}\n${consts}\n\n${record}`);

console.log(
  `codegen: wrote ${patterns.length} patterns to ${path.relative(
    packageRoot,
    outFile
  )}`
);

// ---- catalog.json ----

// Options minus `replace`/`code` - those are css-doodle template plumbing, not
// something a consumer passes. What's left is the id to key `options` by, the
// control type, and the range of accepted values.
const catalogOption = (option) => ({
  id: option.id,
  label: option.displayName,
  type: option.type,
  default: option.default,
  ...(option.options ? { values: option.options } : {}),
  ...(option.min != null ? { min: option.min } : {}),
  ...(option.max != null ? { max: option.max } : {}),
  ...(option.step != null ? { step: option.step } : {}),
  // Present only on ToggleSwitch options, and only while the toggle is on.
  ...(option.svgExportNote ? { svgExportNote: option.svgExportNote } : {}),
});

const { version } = JSON.parse(
  await readFile(path.join(packageRoot, 'package.json'), 'utf-8')
);

const catalog = {
  package: 'tabbied',
  version,
  count: patterns.length,
  docs: 'https://tabbied.com/llms.txt',
  // Repeated once here rather than on every entry. `fit` is deliberately not
  // per-design: every design supports grid / cover / fixed, and an unset one
  // takes the grid default.
  usage: {
    install: 'npm install tabbied',
    import: "import { <slug> } from 'tabbied/patterns';",
    react:
      "import { TabbiedPattern } from 'tabbied/react';\n<TabbiedPattern pattern={<slug>} height={320} />",
    core: "import { createPattern } from 'tabbied';",
    fit: "grid (default) | cover | fixed - the same three for every design",
  },
  designs: patterns.map((definition) => ({
    slug: definition.slug,
    name: definition.name,
    ...(definition.description ? { description: definition.description } : {}),
    // The closed-vocabulary metadata (see catalog-vocabulary.mjs) plus a
    // stable rendered preview, so a tool can query the set on enums and then
    // *look* at its shortlist without running css-doodle.
    tags: definition.tags,
    mood: definition.mood,
    density: definition.density,
    goodFor: definition.goodFor,
    preview: `https://tabbied.com/previews/${definition.slug}.webp`,
    palette: definition.palette ?? [],
    ...(definition.colors ? { colors: definition.colors } : {}),
    options: (definition.options ?? []).map(catalogOption),
    ...(definition.defaultAspectRatio
      ? { defaultAspectRatio: definition.defaultAspectRatio }
      : {}),
    svgExport: {
      // Absent means supported; only the conic-sweep designs opt out.
      supported: definition.svgExport !== false,
      ...(definition.svgExportNote ? { note: definition.svgExportNote } : {}),
    },
  })),
};

await writeFile(catalogFile, `${JSON.stringify(catalog, null, 2)}\n`);

console.log(
  `codegen: wrote catalog for ${patterns.length} designs to ${path.relative(
    packageRoot,
    catalogFile
  )}`
);
